# Generated by Django 4.1.3 on 2023-02-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_alter_profile_user_alter_profile_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumuser',
            name='paid',
            field=models.CharField(choices=[('Yes', 'Yes')], max_length=3),
        ),
    ]
