# Generated by Django 4.1.3 on 2023-02-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_expertlanguage_delete_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertlanguage',
            name='languages',
        ),
        migrations.AddField(
            model_name='expertlanguage',
            name='languages_known',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default=0, max_length=255),
            preserve_default=False,
        ),
    ]
