# Generated by Django 4.1.3 on 2023-02-13 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0006_pendingexpertreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingexpertreview',
            name='pending_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert.room'),
        ),
    ]
