# Generated by Django 4.1.3 on 2023-02-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0007_alter_pendingexpertreview_pending_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertlanguage',
            name='cerificates',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
