# Generated by Django 4.1.3 on 2023-02-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0008_expertlanguage_cerificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertlanguage',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
