# Generated by Django 4.1.3 on 2023-04-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0009_expertlanguage_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='has_attachment',
            field=models.BooleanField(default=False),
        ),
    ]
