# Generated by Django 4.1.3 on 2023-04-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0010_message_attachment_message_has_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='has_attachment',
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
