# Generated by Django 4.1.3 on 2023-04-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0011_remove_message_has_attachment_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='expert/chatmedia/'),
        ),
    ]
