# Generated by Django 4.1.3 on 2023-04-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0012_alter_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='expert_room_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='user_room_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat/'),
        ),
    ]
